version: '3.4'

services:
  pokerdice.api:
    image: ${DOCKER_REGISTRY-}pokerdiceapi
    build:
      context: .
      dockerfile: PokerDice.API/Dockerfile

  pokerdice.db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pokerdice
      MYSQL_DATABASE: pokerdice
    ports:
      - "3306:3306"
    volumes:
      - pokerdice.db-data:/var/lib/mysql

volumes:
  pokerdice.db-data:

