version: '3.4'

services:
  yahtzee.api:
    image: ${DOCKER_REGISTRY-}yahtzeeapi
    build:
      context: .
      dockerfile: Yahtzee.API/Dockerfile

  yahtzee.db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yahtzee
      MYSQL_DATABASE: yahtzee
    ports:
      - "3306:3306"
    volumes:
      - yahtzee.db-data:/var/lib/mysql

volumes:
  yahtzee.db-data: